### ISSUE TITLE
Look-up-table

### ISSUE THREAD

**Issue by ilybend** [gishi523/multilayer-stixel-world#1]
Dear,

I would like to know where did you find the look-up-table of the term P(Cn | Vtn-1, Cn-1) which the authors ommited to mention in their paper due to lack of space.

Ps : Really great job.

**Comment by gishi523** [comment]
Hi,

The look-up-table is written in authors dissertation.
You can get from here.
https://mydlt.de/david/page/publications.html

The Stixel World - A Compact Medium-level Representation for Efficiently Modeling Three-dimensional Environments Table 3.1

Regards,
